### ISSUE TITLE
RFC#2.2: Open API Database

### ISSUE THREAD

**Issue by daviddyess** [Korlimann/MixnJuice#7]
What database do we prefer for the Open API (specifically)? We can always migrate later and I have every intention of providing exports of the data that can be used in various databases.

**Comment by daviddyess** [comment]
MySQL

Please vote here for MySQL to be used.

**Comment by daviddyess** [comment]
PostgreSQL

Please vote here for PgSQL to be used

**Comment by daviddyess** [comment]
MongoDB

Please for here for MongoDB to be used

**Comment by daviddyess** [comment]
Add additional nominations in individual comments for voting. You can vote more than once, but we should reserve that for tie-breakers.

**Comment by pscn** [comment]
Use an ORM that hides what's underneath and start with SQLite.  If we hit a bump in the road, migrate to whatever.  Keep the SQL statements simple, so we can just move to whatever later.

Edit:  Also massively simplifies deployment and testing in the initial phase.

**Comment by ayan4m1** [comment]
Maybe SQLite could be used as part of a unit test suite... but its process model and locking behaviors mean it is entirely unsuited to the work of hosting sites and services intended for consumption by many users. From [Situations Where SQLite Works Well](https://www.sqlite.org/whentouse.html):

> SQLite works great as the database engine for most low to medium traffic websites (which is to say, most websites). The amount of web traffic that SQLite can handle depends on how heavily the website uses its database.

So sure, at the outset this might be a low traffic website. However, I'd argue that this site *is* going to use its database pretty heavily. We will definitely need to sort and paginate large tables over and over again.

The merits (and downsides) of using an ORM and keeping SQL simple are separate and can be applied to any of the relational database technologies. To that end, it might be easy to find an ORM that supports SQLite (for today) and then something like Postgres (for a month from now) - but it might be more difficult to find a good tool that also supports SQLite, so I don't think it should tie us down either way.

From an ops perspective, the single-file (well, plus the .shm and the .wal) database is totally fine if it's a few MB. For even a small database of flavors, users, and recipes, this database will be hundreds of megabytes. The backup strategy isn't as simple as it'd seem, you still need to spin up a tool to write out a consistent snapshot of the flat-file database. And the database gets locked every time someone runs a query. No client/server SQL implementation (from this decade) is as restrictive.

I voted for PostgreSQL because I think it is far and away the fastest and most stable open source SQL server. It supports materialized views as a first class citizen and has better partitioning than MariaDB, both things that help a site deal with data volume and traffic. It has the ability to encrypt individual database columns so that we can protect user info as much as possible while not paying the encryption overhead for every INSERT we do. It

**Comment by pscn** [comment]
ACK.  But I was under the impression, that a read does not lock SQLite.  Is that outdated?

For the rest:  Point taken.

**Comment by ayan4m1** [comment]
@pscn It definitely has the concept of a shared lock, so you're correct in any read-only scenario I can think of. The docs are [fairly complicated](https://www.sqlite.org/draft/lockingv3.html) as you might expect from a database spec, and I have some professional experience with SQLite and its journaling but I've never written a website's worth of traffic to it.

I think the gist is that you can get away with only acquiring a `SHARED` lock state if you're not filling up a journal that already exists, which would be most of the time except under periods of heavy insertion. Issue becomes that as I understand it, when you are doing a lot of inserts/updates you'll be forced to flush that journal eventually, and that means taking out the `PENDING` and `EXCLUSIVE` locks and those can stop a read. If you're pre-allocating a sizable write-ahead log and journal it might be fine but you'd need to tune it and the required allocation size to avoid thrashing would scale linearly with number of concurrent inserts/updates you're receiving.

Maybe I'm missing something obvious there and that is a completely incorrect read of the way it works - I have seen SQLite 3 block reads on a write, but my use case was an odd one, so maybe it wouldn't have been a problem with another application.

**Comment by pscn** [comment]
Thanks for the detailed explanation!

**Comment by pscn** [comment]
Looking at the votes is PostgreSQL.  I wouldn't rule out that we might need a NoSQL DB later on, but think a relational DB is the right choice for the "base" data.  Closing for now.  Please re-open if I'm wrong.
